#!/usr/bin/env bash

export PATH=$HOME/bin/dev-tools/bin:$PATH
export PATH=$HOME/bin/dev-tools/scala3/bin:$PATH
export PATH=$HOME/bin/dev-tools/analyzer:$PATH
export PATH=$HOME/bin/dev-tools/arduino/:$PATH
export PATH=$HOME/bin/dev-tools/spark/bin:$PATH
export PATH=$HOME/bin/dev-tools/cmdline-tools/latest/bin:$PATH
export PATH=$HOME/bin/dev-tools/platform-tools/:$PATH

# Haskell
export PATH=$HOME/.cabal:$PATH

# GPU
export PATH=/usr/local/cuda-9.2/bin:$PATH

# Data Stores
export PATH=/opt/couchbase/bin:$PATH

# Arduino

