#!/usr/bin/env bash

function _update_ps1() {
    PS1=$(powerline-shell $?)
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="$PROMPT_COMMAND _update_ps1; history -a"
fi
