#!/usr/bin/env bash

function _get_password() {
  if [[ -z "${1+set}" ]]; then
    read -p'Password>' -s password 
    echo
  fi
}

alias get_password='_get_password; export PASSWORD=$password; unset password'
