#!/usr/bin/env bash

function _get_password() {
  if [[ -z "${1+set}" ]]; then
    read -p'Password>' -s password 
    echo
  fi
}

function rlf() {
  readlink -f $1 | pbcopy
}

alias get_password='_get_password; export PASSWORD=$password;'
